services:
  llmservices:
    container_name: llms-service
    image: llms:dev
    build: 
      dockerfile: Dockerfile
    restart: always
    volumes:
        - ./app:/home/node/app
        - ../envs/credentials-excel.json:/home/node/app/credentials.json
    env_file:
      - ../envs/llms.env
    ports:
      - "8090:8090"
    networks:
      - db-net
    command: tail -f /home/node/app/package.json
networks:
  db-net:
